version: "2"
services:
  moqui-server:
    build:
      context: simple
      dockerfile: Dockerfile-jdk-11
    container_name: moqui-server
    command: ["java", "-cp", ".", "MoquiStart", "port=8080"]
    restart: always
    links:
     - postgres-database
    ports:
     - "8080:8080"
    environment:
     - instance_purpose=dev
     - entity_ds_db_conf=postgres
     - entity_ds_host=postgres-database
     - entity_ds_port=5430
     - entity_ds_database=moqui
     - entity_ds_user=postgres
     - entity_ds_password=postgres
     - entity_ds_crypt_pass='MoquiDefaultPassword:CHANGEME'
     - webapp_http_host=localhost
     - webapp_http_port=8080
     - webapp_https_port=443
     - webapp_https_enabled=false
     - default_locale=en_US
     - default_time_zone=US/Pacific

  postgres-database:
    image: postgres:14.1-alpine
    container_name: postgres-database
    restart: always
    ports:
      - "127.0.0.1:5430:5430"
    environment:
      - POSTGRES_DB=moqui
      - POSTGRES_DB_SCHEMA=public
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5430
