version: "3.5"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    environment:
      - PORTS=5431

  moqui-load-server:
    image: moqui-load-server
    build:
      context: ./../../..
      dockerfile: docker/gradle-tasks/fill-database/Dockerfile-load-in-build-jdk-11
      args:
        MOQUI_CONF: conf/MoquiLoadConf.xml
        GRADLE_VERSION: 5.6.4
        PG_LOAD_SERVER: docker-host
    container_name: moqui-load-server
    command: ["java", "-cp", ".", "MoquiStart", "port=8080"]
    restart: always
    depends_on:
      - docker-host
    networks:
      - dtq-int
    ports:
     - "8080:8080"

networks:
  dtq-int:
    name: dtq-int